settings:
  legacy:
    force: false
    interval: 10s
schema:
- name: kuncie-backend-test
  path: ./cmd
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - ../
    ignored_paths:
    - .git
    - .realize
    - vendor